import { MODULE_NAME } from './constants';

export const GET_CARDS = `${MODULE_NAME}.GET_CARDS`;
export const GET_CARDS_SUCCESS = `${MODULE_NAME}.GET_CARDS_SUCCESS`;
export const GET_CARDS_FAILURE = `${MODULE_NAME}.GET_CARDS_FAILURE`;

export const OPEN_CARD = `${MODULE_NAME}.OPEN_CARD`;
export const CLOSE_CARDS = `${MODULE_NAME}.CLOSE_CARDS`;
export const SET_PREVIOUS_CARD = `${MODULE_NAME}.SET_PREVIOUS_CARD`;
export const OPEN_SUCCESS = `${MODULE_NAME}.OPEN_SUCCESS`;
export const IS_WIN = `${MODULE_NAME}.IS_WIN`;
export const PLAY = `${MODULE_NAME}.PLAY`;
export const PLAY_AGAIN = `${MODULE_NAME}.PLAY_AGAIN`;
export const SET_CARD_COUNT = `${MODULE_NAME}.SET_CARD_COUNT`;
export const SET_MOVES_COUNT = `${MODULE_NAME}.SET_MOVES_COUNT`;

export const SET_SCORE = `${MODULE_NAME}.SET_SCORE`;
export const SET_SORT_BY = `${MODULE_NAME}.SET_SORT_BY`;
