import { MODULE_NAME } from './constants';

export const GET_CARDS = `${MODULE_NAME}.GET_CARDS`;
export const GET_CARDS_SUCCESS = `${MODULE_NAME}.GET_CARDS_SUCCESS`;
export const GET_CARDS_FAILURE = `${MODULE_NAME}.GET_CARDS_FAILURE`;

export const OPEN_CARD = `${MODULE_NAME}.OPEN_CARD`;
export const CLOSE_CARDS = `${MODULE_NAME}.CLOSE_CARDS`;
export const SET_PREVIOUS_CARD = `${MODULE_NAME}.SET_PREVIOUS_CARD`;
export const OPEN_SUCCESS = `${MODULE_NAME}.OPEN_SUCCESS`;
export const WIN_GAME = `${MODULE_NAME}.WIN_GAME`;
